version = 1

test_patterns = ["tests/*.py"]
exclude_patterns = [".venv", ".git", ".github", ".vscode", ".idea", "dist"]

  [[analyzers]]
name = "python"
dependency_file_paths = ["pyproject.toml"]

[analyzers.meta]
runtime_version = "3.x.x"
